### ISSUE TITLE
Visual design 

### ISSUE THREAD

**Issue by leafo** [khwang/cantaloupe#1]
Discuss how to make the app look good

**Comment by leafo** [comment]
Login dialog from leafo/itchio-app#2

![](http://leafo.net/dump/itchio-app-login.png)

**Comment by leafo** [comment]
Can you give me a screenshot of the updated game listing so I can see what it looks like?

**Comment by leafo** [comment]
Here's something I put together, tell me if right direction.

![](http://leafo.net/dump/app-my-games-small.png)

**Comment by leafo** [comment]
Would it be possible to make graphs that look somewhat like this: http://leafo.net/shotsnb/2015-03-13_22-57-41.png

I don't know what kind of shape primitives you have, but if you can draw convex polygons then it should be good enough, right?

**Comment by catherinemarvin** [comment]
![ios_simulator_-_iphone_6_-_iphone_6___ios_8_2__12d508_](https://cloud.githubusercontent.com/assets/440262/6650773/2a9791c0-c9e1-11e4-9423-f05f7096c269.png)

You mentioned "making the cells smaller", so that's all I did. I moved the text outside and copied the color from your website. I do like your design more though

**Comment by catherinemarvin** [comment]
![screenshot_3_14_15__12_31_am](https://cloud.githubusercontent.com/assets/440262/6650780/6c6d0d14-c9e1-11e4-8324-e3106aa4da25.png)

I'm using a graphing library, but this is what it looks like right now.

**Comment by leafo** [comment]
Want to implement the main screen design I suggested?.

The graph is still horrendous. Can we make it not so tall, make the labels smaller, and use colors from the mock I gave above? Maybe we can work with it. Make the grid lines #DFDFDF, the graph line #DD4A4A, the height around half the width. If you give me another screenshot with those updates I can design a game screen using it.

**Comment by catherinemarvin** [comment]
Give me assets for the main screen and I can work with it

**Comment by leafo** [comment]
There are no assets, unless you don't have access to ios8 icons? Here's an svg with everything: https://github.com/leafo/itchio-app/blob/master/design/app-my-games.svg

**Comment by catherinemarvin** [comment]
I meant to say the login screen :< need the logo and the background image

**Comment by leafo** [comment]
Ah, are you able to get them from the SVG? https://github.com/leafo/itchio-app/blob/master/design/login.svg

**Comment by catherinemarvin** [comment]
I need an Inkscape tutorial :< also a /register API

**Comment by leafo** [comment]
Is register a requirement? I don't think it's a good idea because you can't do anything on the app. I would rather send people to site.

**Comment by leafo** [comment]
Here's the background asset: http://static.itch.io/images/developers/controller.jpg
Here's an SVG version of the white logo, you'll have to rasterize it for ios afaik: http://itch.io/static/images/itchio-white.svg

**Comment by catherinemarvin** [comment]
![games_overview](https://cloud.githubusercontent.com/assets/440262/6840649/0b4aba60-d33a-11e4-95d4-04b2140f3457.png)

Revamped games overview screen

**Comment by catherinemarvin** [comment]
![detailed_graph](https://cloud.githubusercontent.com/assets/440262/6840657/2a38c0a2-d33a-11e4-87be-e8c5549e9b63.png)

Graph view

**Comment by catherinemarvin** [comment]
And I made the detailed game view a bit cleaner.

![detailed_game](https://cloud.githubusercontent.com/assets/440262/6840664/37ae3672-d33a-11e4-977a-3c1aafdacb2a.png)

**Comment by catherinemarvin** [comment]
![login](https://cloud.githubusercontent.com/assets/440262/6840753/f40fe526-d33b-11e4-8c51-7e87841b0599.png)

Login
